<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Nuevo Ingreso PRIMARIA</title>
</head>

<body>
<center>
<div style="width:700px; text-align:justify">
    <p><strong>                              NUEVO INGRESO  CICLO 2012-2013</strong><br />
      <strong>                               COLEGIO CIO DE  MEXICO S.C.</strong></p>
    <p><strong>1º A 6º DE  PRIMARIA: BILINGÜE CONTINUO, MIXTA Y LAICA</strong></p>
    <ul type="disc">
      <li>PRIMERO DE PRIMARIA EL NIÑ@ DEBERÁ  TENER MINIMO 6 AÑOS CUMPLIDOS</li>
      <li>HORARIO DE 7:45 A 14:45</li>
      <li><strong>INSCRIPCION NUEVO INGRESO       INCLUYE SEGURO CONTRA ACCIDENTES        $5,600.00</strong></li>
    </ul>
    <p>              LA INSCRIPCIÓN SE PUEDE  REALIZAR EN DOS PAGOS</p>
    <p>       <strong>COLEGIATURA ( 12 MENSUALIDADES )        $2,758.00</strong><br />
      NOTA IMPORTANTE: AL LLEGAR A 24 ALUMNOS SE CERRARÁ EL  GRUPO<br />
      COMPUTACIÓN, MUSICA, EDUCACIÓN FISICA  (UNA VEZ A LA SEMANA)</p>
    <p>EN CASO DE TENER HERMANITOS EN EL COLEGIO SE OBTENDRÁ  UN BENEFICIO DE BECA DE: <br />
      2º HIJ@ 16%, 3ER HIJ@ 32%, 4º HIJ@ 50% Y 5º  HIJ@ 100%<br />
      ESTE DESCUENTO SERÁ UNO POR FAMILIA OTORGANDOSELO AL  MÁS PEQUEÑO</p>
    <p>EL PAGO DE LA CUOTA ANUAL DE COLEGIATURA TENDRÁ UN 10%  DE DESCUENTO (EN UNA SOLA EXHIBICIÓN)</p>
    <p><strong>TRANSPORTE</strong>:  COMPLETO    $1,400.00<br />
      MEDIO           $1,150.00</p>
    <p><strong>DIARIAMENTE DE  2:00 PM A 2:45 PM LOS ALUM NOS CONTARÁN CON TALLERES OBLIGATORIOS SIN CARGO COMO:  MANUALIDADES, LAB. DE FRANCÉS E INGLÉS, JUEGOS DE DESTREZA, PINTURA, ORATORIA,  TEATRO, INVESTIGACIÓN, MEDIO AMBIENTE, BAILE FOLKLÓRICO, MECANOGRAFÍA,  ACTIVIDADES VIVENCIALES, CORO, PEQUEÑO GOURMET, INTERNET, AQUA AEROBICS, ETC.</strong></p>
    <p><strong>REQUISITOS PARA  INGRESAR A PRIMARIA:</strong></p>
    <p>1.- EL NIÑO SE PRESENTARÁ A UNA ENTREVISTA DE  VALORACIÓN PSICOLÓGICA-COGNITIVA E INGLES, LOS ALUMN@S DE <strong>1ER GRADO</strong> ESTARÁN EN EL COLEGIO UN DÍA DE 9:00 AM A 12:00 PM PARA LOS ALUMNOS <strong>DE 2º A 6º GRADO LA EVALUACIÓN SERÁ TAMBIEN  PARA DEFINIR SU NIVEL DE INGLES CORRESPONDIENTE Y SU APROVECHAMIENTO EN ESPAÑOL</strong> DE LAS 8:00 AM A 13:00 PM PREVIA COITA CON UN COSTO DE <strong>$150.00</strong> PESOS<br />
      2.- LEER Y FIRMAR DE ENTERADO EL REGLAMENTO DEL  COLEGIO (PAPÁ, MAMÁ, ALUMNO)<br />
      3.-  <strong>ORIGINAL Y 3 COPIAS FOTOSTATICAS DE ACTA DE  NACIMIENTO</strong><br />
      4.- <strong>3  FOTOCOPIAS DEL CURP</strong>.<br />
      5.- CERTIFICADO MÉDICO ACTUALIZADO<br />
      6.- <strong>CONSTANCIA  DE ESTUDIOS SEP. AÑO ANTERIOR</strong><br />
      7.- CONTESTAR CUESTIONARIO DEL ALUMN@ ENTRE PAPÁ Y  MAMÁ<br />
      8.- EN CASO DE VENIR DE OTRO COLEGIO ES NECESARIO  PRESENTAR CARTA DE NO ADEUDO Y BUENA CONDUCTA<br />
      9.- <strong>PARA  INICIAR CLASES EL ALUMN</strong><strong>@ </strong><strong>DEBERÁ HABER  ENTREGADO LOS ÚTILES COMPLETOS, LIBROS Y CUADERNOS FORRADOS CON PLÁSTICO  TRANSPARENTE Y MARCADOS CON NOMBRE Y GRADO, TODO LO QUE CONFORME SU UNIFORME  DEBE TENER SU NOMBRE BORDADO.</strong><br />
    </p>
</div>
</center>
</body>
</html>
